#!/usr/bin/env node

/**
 * generate-latex.mjs — Validate and compile a generated .tex CV file to PDF
 *
 * Usage:
 *   node generate-latex.mjs <input.tex> [output.pdf]
 *
 * Reads the .tex file, validates structure, compiles to PDF via tectonic or pdflatex.
 * If output.pdf is omitted, writes to the same directory as input with .pdf extension.
 * The .tex file is generated by the AI agent using templates/cv-template.tex.
 *
 * Requires: tectonic (preferred, brew install tectonic) or pdflatex (MiKTeX / TeX Live) on PATH.
 */

import { readFile, writeFile, stat, copyFile, rm } from 'fs/promises';
import { resolve, basename, dirname, join } from 'path';
import { execFileSync } from 'child_process';
import { existsSync, mkdirSync } from 'fs';

const REQUIRED_SECTIONS = [
  '\\\\section{Education}',
  '\\\\section{Experience}',
  '\\\\section{Projects}',
  '\\\\section{Technical Skills}',
];

const REQUIRED_COMMANDS = [
  '\\\\resumeSubheading',
  '\\\\resumeItem',
  '\\\\resumeProjectHeading',
  '\\\\ResumeSkills',
];

const MIN_COUNTS = {
  resumeItems: 10,
  subheadings: 3,
  projectHeadings: 2,
};

function countPagesFromText(text) {
  const match = text.match(/Output written on[\s\S]*?\((\d+) pages?/i);
  if (match) return Number.parseInt(match[1], 10);
  return 0;
}

function countPdfPages(buffer) {
  const pdfString = buffer.toString('latin1');
  return (pdfString.match(/\/Type\s*\/Page(?!s)\b/g) || []).length;
}

async function main() {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3]; // optional
  if (!inputPath) {
    console.error('Usage: node generate-latex.mjs <input.tex> [output.pdf]');
    process.exit(1);
  }

  const absPath = resolve(inputPath);
  let content;
  try {
    content = await readFile(absPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading ${absPath}: ${err.message}`);
    process.exit(1);
  }

  const issues = [];

  // Check required sections
  for (const pattern of REQUIRED_SECTIONS) {
    if (!new RegExp(pattern).test(content)) {
      issues.push(`Missing section matching: ${pattern}`);
    }
  }

  // Check required commands are used
  for (const cmd of REQUIRED_COMMANDS) {
    if (!new RegExp(cmd).test(content)) {
      issues.push(`Missing command: ${cmd}`);
    }
  }

  // Check document structure
  if (!content.includes('\\begin{document}')) {
    issues.push('Missing \\begin{document}');
  }
  if (!content.includes('\\end{document}')) {
    issues.push('Missing \\end{document}');
  }

  // Check for unresolved placeholders
  const unresolvedMatch = content.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolvedMatch) {
    issues.push(`Unresolved placeholders: ${[...new Set(unresolvedMatch)].join(', ')}`);
  }

  // Check for common unescaped special chars in text (heuristic)
  const lines = content.split('\n');
  let resumeItemCount = 0;
  let subheadingCount = 0;
  let projectHeadingCount = 0;

  for (const line of lines) {
    if (/\\resumeItem\{/.test(line)) resumeItemCount++;
    if (/^\s*\\resumeSubheading\b/.test(line)) subheadingCount++;
    if (/^\s*\\resumeProjectHeading\b/.test(line)) projectHeadingCount++;
  }

  // Check pdfgentounicode
  if (!content.includes('\\pdfgentounicode=1')) {
    issues.push('Missing \\pdfgentounicode=1 (ATS compatibility)');
  }

  if (resumeItemCount < MIN_COUNTS.resumeItems) {
    issues.push(`Resume looks underfilled: found ${resumeItemCount} resume items, expected at least ${MIN_COUNTS.resumeItems}`);
  }
  if (subheadingCount < MIN_COUNTS.subheadings) {
    issues.push(`Missing depth: found ${subheadingCount} subheadings, expected at least ${MIN_COUNTS.subheadings}`);
  }
  if (projectHeadingCount < MIN_COUNTS.projectHeadings) {
    issues.push(`Missing project depth: found ${projectHeadingCount} project headings, expected at least ${MIN_COUNTS.projectHeadings}`);
  }

  const fileInfo = await stat(absPath);
  const sizeKB = (fileInfo.size / 1024).toFixed(1);

  // Output report as JSON
  const report = {
    file: basename(absPath),
    path: absPath,
    sizeKB: parseFloat(sizeKB),
    counts: {
      resumeItems: resumeItemCount,
      subheadings: subheadingCount,
      projectHeadings: projectHeadingCount,
    },
    issues,
    valid: issues.length === 0,
  };

  // If validation fails, report and exit
  if (issues.length > 0) {
    report.valid = false;
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // --- Compile .tex → .pdf ---
  const texDir = dirname(absPath);
  const texBase = basename(absPath, '.tex');
  const defaultPdf = join(texDir, `${texBase}.pdf`);
  const targetPdf = outputPath ? resolve(outputPath) : defaultPdf;

  // Ensure output directory exists
  const targetDir = dirname(targetPdf);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  // Detect available engine: prefer tectonic, fall back to pdflatex
  let engine = null;
  for (const candidate of ['tectonic', 'pdflatex']) {
    try {
      execFileSync(candidate, ['--version'], { stdio: 'pipe' });
      engine = candidate;
      break;
    } catch { /* not found */ }
  }

  if (!engine) {
    report.compiled = false;
    report.compileError = 'No LaTeX engine found. Install tectonic (brew install tectonic) or pdflatex.';
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  report.engine = engine;
  let compileOutput = '';

  // For tectonic: strip pdflatex-only primitives that cause crashes
  let compilePath = absPath;
  if (engine === 'tectonic') {
    const patched = content
      .replace(/\\pdfgentounicode\s*=\s*\d+[^\n]*\n?/g, '')
      .replace(/\\input\{glyphtounicode\}[^\n]*\n?/g, '');
    compilePath = join(texDir, `${texBase}._tectonic.tex`);
    await writeFile(compilePath, patched, 'utf-8');
  }

  try {
    if (engine === 'tectonic') {
      // Tectonic handles multi-pass automatically; --outdir sets output location
      compileOutput = execFileSync('tectonic', ['--outdir', texDir, compilePath], {
        cwd: texDir,
        encoding: 'utf-8',
        timeout: 120_000,
      });
    } else {
      const pdflatexArgs = [
        '-no-shell-escape',
        '-interaction=nonstopmode',
        '-halt-on-error',
        `-output-directory=${texDir}`,
        absPath,
      ];
      // First pass
      compileOutput += execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, encoding: 'utf-8', timeout: 120_000 });
      // Second pass (resolves referenceS))
      compileOutput += execFileSync('pdflatex', pdflatexArgs, { cwd: texDir, encoding: 'utf-8', timeout: 120_000 });
    }

    report.compiled = true;
  } catch (err) {
    const logPath = join(texDir, `${texBase}.log`);
    let latexError = err.message;
    try {
      const log = await readFile(logPath, 'utf-8');
      const errorLines = log.split('\n').filter(l => l.startsWith('!'));
      if (errorLines.length > 0) {
        latexError = errorLines.join('\n');
      }
    } catch { /* no log file */ }

    report.compiled = false;
    report.compileError = latexError;
  }

  // Post-compile: move PDF and clean up (separate from compile errors)
  if (report.compiled) {
    // Tectonic outputs PDF named after the patched temp file
    const compileBase = basename(compilePath, '.tex');
    const compiledPdf = join(texDir, `${compileBase}.pdf`);

    try {
      await copyFile(compiledPdf, targetPdf);
      if (resolve(compiledPdf) !== resolve(targetPdf)) {
        await rm(compiledPdf).catch(() => {});
      }

      const pdfBuffer = await readFile(targetPdf);
      const compileBase = basename(compilePath, '.tex');
      const compiledLogPath = join(texDir, `${compileBase}.log`);
      let compiledLog = '';
      try {
        compiledLog = await readFile(compiledLogPath, 'utf-8');
      } catch { /* log unavailable */ }
      const pageCount = countPagesFromText(`${compileOutput}\n${compiledLog}`) || countPdfPages(pdfBuffer);
      if (pageCount !== 1) {
        report.pageIssue = `Generated PDF has ${pageCount || 'unknown'} pages; expected exactly 1 page. Revise the .tex and rerun.`;
        report.compiled = false;
      }

      const pdfStat = await stat(targetPdf);
      report.pdf = {
        path: targetPdf,
        sizeKB: parseFloat((pdfStat.size / 1024).toFixed(1)),
      };
      report.pages = pageCount;
    } catch (err) {
      report.postCompileError = `Failed to finalize PDF: ${err.message}`;
    }

    // Clean up auxiliary files and tectonic temp .tex (best-effort)
    const auxExts = ['.aux', '.log', '.out', '.fls', '.fdb_latexmk', '.synctex.gz'];
    for (const ext of auxExts) {
      await rm(join(texDir, `${compileBase}${ext}`)).catch(() => {});
    }
    if (engine === 'tectonic') {
      await rm(compilePath).catch(() => {});
    }
  }

  report.valid = report.valid && report.compiled && report.pages === 1 && !report.pageIssue;
  console.log(JSON.stringify(report, null, 2));
  process.exit(report.valid ? 0 : 1);
}

main();
